export const BLOG_LIST_REQUEST = 'BLOG_LIST_REQUEST'
export const BLOG_LIST_SUCCESS = 'BLOG_LIST_SUCCESS'
export const BLOG_LIST_FAILURE = 'BLOG_LIST_FAILURE'

export const BLOG_BY_ID_REQUEST = 'BLOG_BY_ID_REQUEST'
export const BLOG_BY_ID_SUCCESS = 'BLOG_BY_ID_SUCCESS'
export const BLOG_BY_ID_FAILURE = 'BLOG_BY_ID_FAILURE'

export const BLOG_ADD_REQUEST = 'BLOG_ADD_REQUEST'
export const BLOG_ADD_SUCCESS = 'BLOG_ADD_SUCCESS'
export const BLOG_ADD_FAILURE = 'BLOG_ADD_FAILURE'

export const BLOG_DELETE_REQUEST = 'BLOG_DELETE_REQUEST'
export const BLOG_DELETE_SUCCESS = 'BLOG_DELETE_SUCCESS'
export const BLOG_DELETE_FAILURE = 'BLOG_DELETE_FAILURE'

export const BLOG_UPDATE_REQUEST = 'BLOG_UPDATE_REQUEST'
export const BLOG_UPDATE_SUCCESS = 'BLOG_UPDATE_SUCCESS'
export const BLOG_UPDATE_FAILURE = 'BLOG_UPDATE_FAILURE'

export const BLOG_GENERAL_REQUEST = 'BLOG_GENERAL_REQUEST'
export const BLOG_GENERAL_SUCCESS = 'BLOG_GENERAL_SUCCESS'
export const BLOG_GENERAL_FAILURE = 'BLOG_GENERAL_FAILURE'